### ISSUE TITLE
Can't pass custom renderer constructor to state

### ISSUE THREAD

**Issue by eXponenta** [pmndrs/react-ogl#10]
Follow props signature, we able to use a custom renderer, but it not make sense because we can't pass canvas reference, because canvas not exist when we create it.

https://github.com/pmndrs/react-ogl/blob/main/src/shared/utils.ts#L105

Need to allow use a functional argument of rendere that will return instance for allowing this:
![image](https://user-images.githubusercontent.com/12572222/159118356-24bb07d4-ef7c-4c7c-a054-1c37d54e7575.png)

Like this:
https://github.com/pmndrs/react-three-fiber/blob/0fd9337565e7ae264b539b0ef9be05c04f749b89/packages/fiber/src/web/index.tsx#L39

**Comment by CodyJasonBennett** [comment]
Fix published in [`v0.1.2`](https://github.com/pmndrs/react-ogl/releases/tag/v0.1.2).
