### ISSUE TITLE
[feature] Dispose

### ISSUE THREAD

**Issue by eXponenta** [pmndrs/react-ogl#14]
Dispose is required because we can't know when React kill node or only replace it.
For mesh this is critical, because Geometry allocating GPU memory, Textures too, and other GL objects.

Suggest add to this:
https://github.com/pmndrs/react-ogl/blob/main/src/reconciler.ts#L121

Or remove call:

https://github.com/oframe/ogl/blob/master/src/core/Program.js#L208
https://github.com/oframe/ogl/blob/master/src/core/Geometry.js#L266

Or `dispose` call with nullish check, `dispose` or `destroy` is convential, and can be implemented in subclasses.

**Comment by CodyJasonBennett** [comment]
Implemented in #13.
