### ISSUE TITLE
useLoader equivalent

### ISSUE THREAD

**Issue by TiagoCavalcante** [pmndrs/react-ogl#20]
`useLoader` is an important feature in R3F, it would be very useful here too.

Code:
https://github.com/pmndrs/react-three-fiber/blob/48f378fb3896dc0232c7bca117abb2b67c75f21c/packages/fiber/src/core/hooks.tsx#L88-L127

**Comment by CodyJasonBennett** [comment]
This needs documentation but each target has its own hooks export -- it's a bit more involved than R3F which can use a single signature.
