### ISSUE TITLE
codesandbox CI

### ISSUE THREAD

**Issue by gsimone** [pmndrs/react-ogl#3]
Would you like me to setup CI like maath? sandboxes in demo/src/sandboxes that can be used for dev ( I do it with a router in the demo ) and deployed to CSB CI for testing/examples

eg. https://github.com/pmndrs/maath/tree/main/demo/src/sandboxes/points ->  [ 📦  Codesandbox](https://githubbox.com/pmndrs/maath/tree/main/demo/src/sandboxes/points) 

This would also get deployed at CI with the package built from the PR (like we do in r3f, drei & leva too)

**Comment by CodyJasonBennett** [comment]
Yes, that would be great!
