### ISSUE TITLE
react-devtools crash

### ISSUE THREAD

**Issue by controversial** [pmndrs/react-ogl#4]
When I inspect any `react-ogl` elements in devtools (React Developer Tools version 4.23.0) devtools crashes with an error that it “Could not find ID for Fiber <Component>” (where <Component> is the name of the react-dom component that renders `<Canvas />`).

<img width="901" alt="Screen Shot 2022-02-22 at 12 23 55 PM" src="https://user-images.githubusercontent.com/10377391/155185248-e148b488-fbf6-424c-b03f-12dba7936b1f.png">

**Comment by CodyJasonBennett** [comment]
I've seen this before with R3F and it seems react-ogl is perhaps misusing a reconciler hook.

In R3F, to register the reconciler with devtools:

```js
// r3f v7, master
reconciler.injectIntoDevTools({
  bundleType: process.env.NODE_ENV === 'production' ? 0 : 1,
  rendererPackageName: '@react-three/fiber',
  version: '17.0.2',
})
```

In react-ogl:

```js
reconciler.injectIntoDevTools({
  bundleType: process.env.NODE_ENV === 'production' ? 0 : 1,
  rendererPackageName: 'react-ogl',
  version: '0.1.0',
})
```

**Comment by CodyJasonBennett** [comment]
I published 0.0.8 with R3F's usage to test.

**Comment by CodyJasonBennett** [comment]
Which version of devtools are you on? If you want to dig deeper, cloning the repo and running the demo locally will run directly from the source.

**Comment by eXponenta** [comment]
Reproduced!

DevTool version - latest chrome store version.
React - 17.0.1

Tree:

```jsx

const App = () => (
<Strict>
     <Canvas> <AnyOglNode/> </Canvas>
     <div/>
</Strict>)
```

When there are a sub-renderer in parallel tree - devtool crash when you try select a AnyOglNode from it with fiber error. 
I going to try solve this, because this blocking quality control for me.

Looks like that devtool traversing a fiber nodes from child to root and there are a disconnection.

**Comment by controversial** [comment]
I'm also using the latest version of devtools

**Comment by CodyJasonBennett** [comment]
I'm not able to reproduce this using the demo in this repo (also mirroring your repros above). Which versions of react & react-dom are you testing on? AFAIK react-ogl has to report the same versions to devtools.

**Comment by CodyJasonBennett** [comment]
Is this still an issue? I still can't reproduce this on my end.

**Comment by CodyJasonBennett** [comment]
I've improved internal handling of fiber switching and devtools config with [`0.2.0`](https://github.com/pmndrs/react-ogl/releases/tag/v0.2.0). Can anyone see if this issue still persists?
