### ISSUE TITLE
OGL TextureLoader and react-ogl useLoader are incompatible

### ISSUE THREAD

**Issue by awesomechoi11** [pmndrs/react-ogl#69]
useLoader passes url as `url` but TextureLoader only accepts `src`

https://github.com/oframe/ogl/blob/b9817c6b207507365471c8af0387e0df16a3f843/src/extras/TextureLoader.js#L13

https://github.com/pmndrs/react-ogl/blob/075f0825ac258143f2e51365fd70fa971b9da84f/src/hooks.ts#L126

```
urls.map(async (url: string) => {
  // @ts-ignore OGL's loaders don't have a consistent signature
  if (classExtends(loader, OGL.TextureLoader)) return loader.load(gl, { url })
  
  return await loader.load(gl, url)
}),
```

**Comment by CodyJasonBennett** [comment]
Fix out in [`v0.9.1`](https://github.com/pmndrs/react-ogl/releases/tag/v0.9.1). We'll have to add coverage there, API is very fragile.
